### PR TITLE
Checkpoint 5 | Create To-Do Items

### PR DESCRIPTION
**Pull request by Isangidien**
I'm getting this error on this line in localhost.    ` <%= render partial: 'items/item', collection: @items %>` it says that's its located in my app/views/users/show.html.erb:12:
I made some changes trying to follow a little closer to another assignment and everything was working until I tried to add the partial.

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@Isangidien 

Your file is named wrong: app/views/items/_item.htm.erb

Should be: app/views/items/_item.html.erb

Also, you can shorten the line to: 

```
<%= render @items %>
```

**Comment by brittanyjspringer** [comment]
@Isangidien I'm not doing anything with this pull request unless you message me here for another review. Please keep me posted. Also if this becomes an official review, please clean up the title and description of this pull request.

**Comment by Isangidien** [comment]
Added some style and corrected some issues with the view.  PR now ready for official review.

**Review by brittanyjspringer — COMMENTED** [review]
Inessa, I'd like to see tests for the ItemsController.

**Comment by brittanyjspringer** [comment]
@Isangidien I updated the title of the pull request. Please reassign the pull request to me when you have the tests written.

**Comment by Isangidien** [comment]
When setting up a test for items controller do I also need to create a DB seed?  Seeding is at the next checkpoint so I'm a little confused. In looking back at other assignments seeding was done in order to complete the item test.

**Comment by brittanyjspringer** [comment]
Hi @Isangidien -- no you need to make factories, not seeds. You use the Faker gem for both.

**Comment by Isangidien** [comment]
Still, receiving the deprecation warning after changing FactoryBot to FactoryGirl.  Also, same failures when running bundle exec rspec spec that was in last nights review.

**Comment by brittanyjspringer** [comment]
@Isangidien I won't be able to fix it unless you push up the code we worked on together to this branch. Please ping me when you do so.

**Comment by brittanyjspringer** [comment]
@Isangidien 

1. Tests are working great. You had both factory_girl and factory_bot_rails which causing naming issues. 
2. I fixed the routing to your ItemsController tests
3. Added Item models tests
4. Added your /coverage folder to .gitignore so it won't get committed anymore. 

Test coverage: 154 / 178 LOC (86.52%) covered.

Merging, please check out locally to master and pull down before moving on. Cheers!

**Pull request merged**
